camera/media: Support for legacy camera HALv1 Pre 7.0 camera HALv1 can not share its video buffers across different processes, which requires us to disable this security feature.
This change allows devices to re-integrate cameraserver
and mediaserver which is the first step to support older
prebuilt camera HALs. A follow-up change will add back
support for legacy buffer handling.

To enable:
TARGET_HAS_LEGACY_CAMERA_HAL1 := true
media.stagefright.legacyencoder=true
media.stagefright.less-secure=true

mediaserver: Update HALv1 dependencies for 8.0.0

 * Add libcameraservice shared library dependency
 * Add new android.hardware.camera.common@1.0 and
    android.hardware.camera.provider@2.4 shared
    libraries and exported headers HAL dependencies

 * Add libarect static library dependency

 * When TARGET_HAS_LEGACY_CAMERA_HAL1 is set, the mediaserver
    includes CameraService.h but exported headers are missing

 * Error upon build due to missing libcameraservice linkage:
    fatal error: 'android/hardware/BnCameraService.h' file not found

Change-Id: I9bbeadbecd4342ae93bc3c3db31c66144a5f0896
Signed-off-by: nailyk-fr <jenkins@nailyk.fr>
Author
Simon Shields <keepcalm444@gmail.com>
Oct 6, 2016 10:25 AM
Committer
nailyk-fr <jenkins@nailyk.fr>
Oct 27, 2017 11:30 AM